version: '3.7'

services:
  pgbackups3:
    image: schickling/postgres-backup-s3
    environment:
      SCHEDULE: '@daily'
      S3_REGION: 'region'
      S3_ACCESS_KEY_ID: 'key'
      S3_SECRET_ACCESS_KEY: 'secret'
      S3_BUCKET: 'my-bucket'
      S3_PREFIX: 'backup'
      POSTGRES_DATABASE: 'dbname'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST: 'host'
